/**
 * Domain configuration for Discovered Database
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "discovered-database",
  name: "Discovered Database",
  description: "Ontology discovered from an existing Neo4j database",
  tagline: "AI-powered graph intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export const NODE_COLORS: Record<string, string> = {"Appearance": "#2563eb", "Attack": "#dc2626", "Block": "#16a34a", "Chat": "#9333ea", "ChatSession": "#ea580c", "Dig": "#0891b2", "Event": "#be123c", "Freeball": "#4f46e5", "GameInterruption": "#65a30d", "League": "#c026d3", "Match": "#0d9488", "Player": "#ca8a04", "Rally": "#7c3aed", "Reception": "#0284c7", "RotationState": "#db2777", "Serve": "#059669", "Set": "#b45309", "SetAction": "#475569", "Staff": "#e11d48", "Stats": "#0f766e", "Substitution": "#2563eb", "Tactic": "#dc2626", "Team": "#16a34a", "XAFactor": "#9333ea"};

export const NODE_SIZES: Record<string, number> = {"Appearance": 20, "Attack": 20, "Block": 20, "Chat": 20, "ChatSession": 20, "Dig": 20, "Event": 20, "Freeball": 20, "GameInterruption": 20, "League": 20, "Match": 20, "Player": 20, "Rally": 20, "Reception": 20, "RotationState": 20, "Serve": 20, "Set": 20, "SetAction": 20, "Staff": 20, "Stats": 20, "Substitution": 20, "Tactic": 20, "Team": 20, "XAFactor": 20};

export const DEFAULT_CYPHER = "MATCH (n:`Appearance`) RETURN n LIMIT 100";

export const SCHEMA_NODE_SIZE = 30;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Explore discovered graph", "prompts": ["Show me a few Appearance records and summarize the key properties.", "What relationships connect Appearance to other labels in this graph?", "Compare Appearance with Attack using available relationships.", "Find examples that use the AWAY_ROTATION relationship."]}];
