"""Domain models for Discovered Database — auto-generated from ontology."""

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field

class Appearance(BaseModel):
    """Entity model for Appearance."""

    id: str = ...
    date: str = ...
    jersey_number: str = ...
    role_in_match: str = ...

class Attack(BaseModel):
    """Entity model for Attack."""

    id: str = ...
    team_code: str = ...
    player_id: str | None = None
    rally_id: str = ...
    match_id: str = ...
    team_score: str = ...
    opponent_score: str = ...
    tactic_code: str | None = None
    start_zone_id: str | None = None
    end_zone_id: str | None = None
    hit_type: str = ...
    possession_number: str = ...
    phase: str | None = None
    start_location: str | None = None
    end_location: str | None = None
    end_sub_zone: str | None = None
    effect: str = ...
    team_setter_position: str = ...
    xa_setter_zone: str | None = None
    fastrp_embedding: str | None = None
    effect_weight: str = ...
    sequence_number: str = ...
    xa_scope: str | None = None
    xa: str | None = None
    set_number: str = ...
    vsm_code: str | None = None
    original_time_ms: str | None = None
    time_video_ms: str | None = None
    tactic_category: str | None = None
    players_in_block: str | None = None
    skill_type: str | None = None
    start_sub_zone: str | None = None
    n2v_embedding: str | None = None

class Block(BaseModel):
    """Entity model for Block."""

    id: str = ...
    team_code: str = ...
    player_id: str | None = None
    rally_id: str = ...
    match_id: str = ...
    team_score: str = ...
    opponent_score: str = ...
    start_zone_id: str | None = None
    end_zone_id: str | None = None
    hit_type: str = ...
    possession_number: str = ...
    phase: str | None = None
    start_location: str | None = None
    end_location: str | None = None
    end_sub_zone: str | None = None
    effect: str = ...
    set_number: str = ...
    vsm_code: str | None = None
    original_time_ms: str | None = None
    time_video_ms: str = ...
    team_setter_position: str = ...
    players_count: str | None = None
    fastrp_embedding: str | None = None
    start_sub_zone: str | None = None
    skill_type: str | None = None
    effect_weight: str = ...
    sequence_number: str = ...
    n2v_embedding: str | None = None

class Chat(BaseModel):
    """Entity model for Chat."""

    id: str = ...
    thinking_steps: str | None = None
    llm_calls: str | None = None
    prompt_tokens: str | None = None
    total_tokens: str | None = None
    seq: str = ...
    step_details: str | None = None
    execution_time_ms: str | None = None
    timestamp: str = ...
    cost_usd: str | None = None
    role: str = ...
    completion_tokens: str | None = None
    model: str | None = None
    content: str = ...
    queries_count: str | None = None

class ChatSession(BaseModel):
    """Entity model for ChatSession."""

    id: str = ...
    hidden_at: str | None = None
    title: str = ...
    created_at: str = ...
    hidden: str = ...

class Dig(BaseModel):
    """Entity model for Dig."""

    id: str = ...
    team_code: str = ...
    player_id: str | None = None
    rally_id: str = ...
    match_id: str = ...
    team_score: str = ...
    opponent_score: str = ...
    start_zone_id: str | None = None
    end_zone_id: str | None = None
    hit_type: str = ...
    possession_number: str = ...
    phase: str | None = None
    start_location: str | None = None
    end_location: str | None = None
    end_sub_zone: str | None = None
    effect: str = ...
    set_number: str = ...
    vsm_code: str | None = None
    original_time_ms: str | None = None
    time_video_ms: str | None = None
    team_setter_position: str = ...
    skill_type: str | None = None
    fastrp_embedding: str | None = None
    start_sub_zone: str | None = None
    effect_weight: str = ...
    sequence_number: str = ...
    n2v_embedding: str | None = None

class Event(BaseModel):
    """Entity model for Event."""

    id: str = ...
    team_code: str = ...
    player_id: str | None = None
    rally_id: str = ...
    match_id: str = ...
    team_score: str = ...
    opponent_score: str = ...
    tactic_code: str | None = None
    start_zone_id: str | None = None
    end_zone_id: str | None = None
    hit_type: str = ...
    possession_number: str = ...
    phase: str | None = None
    start_location: str | None = None
    end_location: str | None = None
    end_sub_zone: str | None = None
    effect: str = ...
    set_number: str = ...
    vsm_code: str | None = None
    original_time_ms: str | None = None
    time_video_ms: str | None = None
    team_setter_position: str = ...
    skill_type: str | None = None
    fastrp_embedding: str | None = None
    start_sub_zone: str | None = None
    effect_weight: str = ...
    sequence_number: str = ...
    n2v_embedding: str | None = None
    target_attacker_role: str | None = None
    xa_setter_zone: str | None = None
    xa_scope: str | None = None
    xa: str | None = None
    tactic_category: str | None = None
    players_in_block: str | None = None
    players_count: str | None = None

class Freeball(BaseModel):
    """Entity model for Freeball."""

    id: str = ...
    team_code: str = ...
    player_id: str | None = None
    rally_id: str = ...
    match_id: str = ...
    team_score: str = ...
    opponent_score: str = ...
    tactic_code: str | None = None
    start_zone_id: str | None = None
    end_zone_id: str | None = None
    hit_type: str = ...
    possession_number: str = ...
    phase: str | None = None
    start_location: str | None = None
    end_location: str | None = None
    end_sub_zone: str | None = None
    effect: str = ...
    set_number: str = ...
    vsm_code: str | None = None
    original_time_ms: str | None = None
    time_video_ms: str | None = None
    team_setter_position: str = ...
    fastrp_embedding: str | None = None
    start_sub_zone: str | None = None
    skill_type: str | None = None
    effect_weight: str = ...
    sequence_number: str = ...
    n2v_embedding: str | None = None

class GameInterruption(BaseModel):
    """Entity model for GameInterruption."""

    id: str = ...
    type: str = ...
    team: str = ...
    score_away: str = ...
    score_home: str = ...
    sequence_number: str = ...

class League(BaseModel):
    """Entity model for League."""

    name: str = ...
    gender: str = ...
    country: str | None = None
    type: str = ...

class Match(BaseModel):
    """Entity model for Match."""

    id: str = ...
    date: str = ...
    game_type: str = ...
    vsm_version: str = ...
    video_path: str | None = None
    winner_team_id: str = ...
    hall: str | None = None
    league: str = ...
    stage: str = ...
    city: str | None = None
    season: str = ...
    score: str = ...

class Player(BaseModel):
    """Entity model for Player."""

    id: str = ...
    embedding: str | None = None
    code: str = ...
    last_name: str = ...
    first_name: str = ...
    primary_position: str = ...
    is_foreign: str | None = None
    alt_codes: str | None = None

class Rally(BaseModel):
    """Entity model for Rally."""

    id: str = ...
    winning_team_id: str | None = None
    pattern_embedding: str | None = None
    score_away_before: str = ...
    duration_sec: str | None = None
    setter_position_away: str = ...
    score_home_before: str = ...
    setter_position_home: str = ...
    pattern_cluster: str | None = None
    start_time_video_ms: str | None = None

class Reception(BaseModel):
    """Entity model for Reception."""

    id: str = ...
    team_code: str = ...
    player_id: str | None = None
    rally_id: str = ...
    match_id: str = ...
    team_score: str = ...
    opponent_score: str = ...
    start_zone_id: str | None = None
    end_zone_id: str | None = None
    hit_type: str = ...
    possession_number: str = ...
    phase: str | None = None
    start_location: str | None = None
    end_location: str | None = None
    end_sub_zone: str | None = None
    effect: str = ...
    set_number: str = ...
    vsm_code: str | None = None
    original_time_ms: str | None = None
    time_video_ms: str | None = None
    team_setter_position: str = ...
    skill_type: str | None = None
    fastrp_embedding: str | None = None
    start_sub_zone: str | None = None
    effect_weight: str = ...
    sequence_number: str = ...
    n2v_embedding: str | None = None

class RotationState(BaseModel):
    """Entity model for RotationState."""

    hash: str = ...

class Serve(BaseModel):
    """Entity model for Serve."""

    id: str = ...
    team_code: str = ...
    player_id: str | None = None
    rally_id: str = ...
    match_id: str = ...
    team_score: str = ...
    opponent_score: str = ...
    tactic_code: str | None = None
    start_zone_id: str | None = None
    end_zone_id: str | None = None
    hit_type: str = ...
    possession_number: str = ...
    phase: str | None = None
    start_location: str | None = None
    end_location: str | None = None
    end_sub_zone: str | None = None
    effect: str = ...
    set_number: str = ...
    vsm_code: str | None = None
    original_time_ms: str | None = None
    time_video_ms: str | None = None
    team_setter_position: str = ...
    skill_type: str | None = None
    fastrp_embedding: str | None = None
    start_sub_zone: str | None = None
    effect_weight: str = ...
    sequence_number: str = ...
    n2v_embedding: str | None = None

class Set(BaseModel):
    """Entity model for Set."""

    id: str = ...
    number: str = ...
    score_away: str = ...
    score_home: str = ...

class SetAction(BaseModel):
    """Entity model for SetAction."""

    id: str = ...
    team_code: str = ...
    player_id: str | None = None
    rally_id: str = ...
    match_id: str = ...
    team_score: str = ...
    opponent_score: str = ...
    tactic_code: str | None = None
    start_zone_id: str | None = None
    end_zone_id: str | None = None
    hit_type: str = ...
    possession_number: str = ...
    phase: str | None = None
    start_location: str | None = None
    end_location: str | None = None
    target_attacker_role: str | None = None
    end_sub_zone: str | None = None
    effect: str = ...
    set_number: str = ...
    vsm_code: str | None = None
    original_time_ms: str | None = None
    time_video_ms: str | None = None
    team_setter_position: str = ...
    fastrp_embedding: str | None = None
    skill_type: str | None = None
    start_sub_zone: str | None = None
    effect_weight: str = ...
    sequence_number: str = ...
    n2v_embedding: str | None = None

class Staff(BaseModel):
    """Entity model for Staff."""

    id: str = ...
    last_name: str = ...
    first_name: str = ...
    role: str = ...

class Stats(BaseModel):
    """Entity model for Stats."""

    id: str = ...
    team_code: str | None = None
    player_id: str | None = None
    home_points_from_attack: str | None = None
    team_id: str | None = None
    atk_efficiency: str | None = None
    atk_pos4_errors: str | None = None
    home_errors: str | None = None
    max_rally_duration_sec: str | None = None
    home_rec_total: str | None = None
    atk_pos5_efficiency: str | None = None
    fb_errors: str | None = None
    atk_so_total: str | None = None
    home_atk_kills: str | None = None
    atk_pos3_efficiency: str | None = None
    atk_pos6_total: str | None = None
    home_atk_xa: str | None = None
    home_dig_total: str | None = None
    rec_positive: str | None = None
    blk_kills: str | None = None
    streak_current_error_free_serve: str | None = None
    atk_kill_pct: str | None = None
    dig_perfect: str | None = None
    atk_pos1_kills: str | None = None
    pr_points_scored: str | None = None
    atk_pos1_efficiency: str | None = None
    atk_xa: str | None = None
    avg_rally_duration_sec: str | None = None
    atk_positive: str | None = None
    away_atk_xa: str | None = None
    atk_pos2_kills: str | None = None
    atk_blocked: str | None = None
    away_bp_pct: str | None = None
    home_points_from_serve: str | None = None
    home_bp_pct: str | None = None
    points_scored: str | None = None
    atk_pos3_kills: str | None = None
    streak_best_double_digit_kills: str | None = None
    total_sets: str | None = None
    home_points_from_block: str | None = None
    away_errors: str | None = None
    atk_per_set: str | None = None
    atk_xa_coverage: str | None = None
    blk_total: str | None = None
    pr_srv_aces: str | None = None
    blk_positive: str | None = None
    scope: str = ...
    away_atk_errors: str | None = None
    away_points_from_attack: str | None = None
    away_atk_efficiency: str | None = None
    pr_set_assists: str | None = None
    atk_pos1_total: str | None = None
    home_srv_total: str | None = None
    streak_best_efficiency_50: str | None = None
    away_rec_total: str | None = None
    aces_per_set: str | None = None
    blk_per_set: str | None = None
    away_srv_errors: str | None = None
    set_errors: str | None = None
    atk_pos3_errors: str | None = None
    set_assists: str | None = None
    rec_total: str | None = None
    atk_pos5_kills: str | None = None
    rec_perfect_pct: str | None = None
    lead_changes: str | None = None
    atk_pos5_errors: str | None = None
    away_dig_total: str | None = None
    season: str | None = None
    atk_transition_total: str | None = None
    atk_pos4_total: str | None = None
    srv_total: str | None = None
    home_srv_aces: str | None = None
    atk_pos2_total: str | None = None
    away_atk_total: str | None = None
    atk_pos6_kills: str | None = None
    home_atk_efficiency: str | None = None
    srv_efficiency: str | None = None
    away_atk_kills: str | None = None
    away_srv_total: str | None = None
    away_points_from_block: str | None = None
    atk_kae: str | None = None
    pr_blk_kills: str | None = None
    streak_best_error_free_serve: str | None = None
    streak_current_double_digit_kills: str | None = None
    blk_errors: str | None = None
    streak_current_double_digit_points: str | None = None
    dig_positive: str | None = None
    atk_so_efficiency: str | None = None
    away_srv_aces: str | None = None
    seasons_played: str | None = None
    atk_errors: str | None = None
    away_points_from_serve: str | None = None
    rec_errors: str | None = None
    teams_played_for: str | None = None
    is_tiebreak: str | None = None
    total_errors: str | None = None
    atk_xa_count: str | None = None
    streak_current_efficiency_50: str | None = None
    atk_pos4_efficiency: str | None = None
    streak_best_aces: str | None = None
    away_dig_positive_pct: str | None = None
    total_rallies: str | None = None
    atk_kills: str | None = None
    atk_total: str | None = None
    sets_played: str | None = None
    atk_so_kills: str | None = None
    pr_atk_efficiency: str | None = None
    atk_bp_kills: str | None = None
    atk_bp_total: str | None = None
    atk_pos2_errors: str | None = None
    atk_pos6_errors: str | None = None
    atk_pos3_total: str | None = None
    max_point_streak_home: str | None = None
    home_rec_positive_pct: str | None = None
    away_so_pct: str | None = None
    home_atk_total: str | None = None
    atk_pos1_errors: str | None = None
    total_points: str | None = None
    dig_total: str | None = None
    points_per_set: str | None = None
    atk_bp_errors: str | None = None
    away_rec_positive_pct: str | None = None
    home_atk_kae: str | None = None
    atk_pos4_kills: str | None = None
    atk_so_errors: str | None = None
    srv_aces: str | None = None
    set_positive: str | None = None
    atk_bp_efficiency: str | None = None
    rec_perfect: str | None = None
    fb_total: str | None = None
    matches_played: str | None = None
    home_srv_errors: str | None = None
    atk_pos5_total: str | None = None
    total_actions: str | None = None
    atk_kae_per_set: str | None = None
    streak_best_double_digit_points: str | None = None
    rec_efficiency: str | None = None
    home_so_pct: str | None = None
    away_atk_kae: str | None = None
    away_blk_kills: str | None = None
    home_dig_positive_pct: str | None = None
    atk_pos2_efficiency: str | None = None
    srv_positive: str | None = None
    home_atk_errors: str | None = None
    pr_atk_kills: str | None = None
    rec_positive_pct: str | None = None
    pr_rec_positive_pct: str | None = None
    rec_per_set: str | None = None
    milestones: str | None = None
    home_blk_kills: str | None = None
    max_point_streak_away: str | None = None
    atk_transition_kills: str | None = None
    streak_current_aces: str | None = None
    dig_errors: str | None = None
    point_ratio: str | None = None
    points_lost: str | None = None
    srv_ace_pct: str | None = None
    set_total: str | None = None
    srv_errors: str | None = None
    atk_pos6_efficiency: str | None = None

class Substitution(BaseModel):
    """Entity model for Substitution."""

    id: str = ...
    team: str = ...
    score_away: str = ...
    score_home: str = ...
    sequence_number: str = ...

class Tactic(BaseModel):
    """Entity model for Tactic."""

    id: str = ...
    hit_type: str | None = None
    name: str = ...
    code: str = ...
    target_attacker_role: str | None = None
    start_sub_zone: str | None = None
    start_zone: str | None = None
    type: str = ...
    category: str | None = None

class Team(BaseModel):
    """Entity model for Team."""

    id: str = ...
    tactical_embedding: str = ...
    name: str = ...
    short_code: str = ...
    code: str = ...
    type: str = ...

class XAFactor(BaseModel):
    """Entity model for XAFactor."""

    id: str = ...
    team_code: str | None = None
    tactic_code: str = ...
    hit_type: str = ...
    phase: str = ...
    rq_excl: str = ...
    rq_plus: str = ...
    rq_none: str = ...
    league: str = ...
    rq_eq: str = ...
    updated_at: str = ...
    season: str | None = None
    scope: str = ...
    rq_minus: str = ...
    rq_slash: str = ...
    rec_quality_score: str | None = None
    n_attacks: str = ...
    rq_hash: str = ...
    kill_pct: str = ...
    setter_zone: str = ...

